
listen_addresses = ['127.0.0.1:53']

max_clients = 250

ipv4_servers = true

ipv6_servers = false

dnscrypt_servers = true

doh_servers = true


require_dnssec = false

require_nolog = true

require_nofilter = true

force_tcp = false

timeout = 2500

keepalive = 30

lb_strategy = 'fastest'

use_syslog = false

cert_refresh_delay = 240

fallback_resolver = '114.114.114.114:53'
ignore_system_dns = false


netprobe_timeout = 30
log_files_max_size = 10

log_files_max_age = 7

log_files_max_backups = 1

block_ipv6 = true

cache = true

cache_size = 512

cache_min_ttl = 600

cache_max_ttl = 86400

cache_neg_min_ttl = 60

cache_neg_max_ttl = 600

[query_log]


file = 'query.log'

format = 'tsv'

[nx_log]

file = 'nx.log'

format = 'tsv'

[blacklist]

[ip_blacklist]

[whitelist]

[schedules]

[sources]

[static]
[static.'dns.rubyfish.cn']
stamp = 'sdns://AgcAAAAAAAAAAAAPZG5zLnJ1YnlmaXNoLmNuCi9kbnMtcXVlcnk'

